name: Build for CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]

jobs:
  build-plugin-ci:

    runs-on: windows-latest
    
    steps:
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 9.0
      
    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources
    
    - uses: actions/checkout@v4
    - name: Build
      run: dotnet build src\Plugin.Maui.DebugRainbows.sln -c Release
